### PR TITLE
Documentation/update readme

### LINKED ISSUE #360: Update Readme Documentation
As a user of `mi`,
I want to have proper updated documentation on how to use `mi` for GH data inspection/metrics calculation,
so that I can use `mi` for (my) repository analysis.

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Closes #360 

## This introduces a breaking change

- [ ] Yes
- [x] No

## Description

Update documentation

### CODE REVIEW

**Comment by xtuchyna** [comment]
hello @pacospace :wave: ! Maybe some ideas that could be propagated into this ?!

**Review by harshad16 — COMMENTED** [review]
/lgtm
nice work :100:

**Comment by xtuchyna** [comment]
> /lgtm
> nice work 100

lgtm'ed, approving the PR
/approve

**Pull request merged**
