### PR TITLE
Add requirements for PyPI, remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by xtuchyna**

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
missing `requirements.txt`

**Comment by xtuchyna** [comment]
damn you fast man!

**Comment by pacospace** [comment]
Not sure if we want all the requirements locked in requirements.txt, cc @fridex

**Comment by pacospace** [comment]
> Not sure if we want all the requirements locked in requirements.txt, cc @fridex

Also not sure that you can use that requirements.txt with the method in setup.py

**Comment by xtuchyna** [comment]
I've did it as other repositories have, will do patch release after merge and see if it's okay

**Review by pacospace — APPROVED** [review]
lgtm!

**Pull request merged**
